export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";

export const API_CALL_REQUEST_ONE_POST = "API_CALL_REQUEST_ONE_POST";
export const API_CALL_SUCCESS_ONE_POST = "API_CALL_SUCCESS_ONE_POST";
export const API_CALL_FAILURE_ONE_POST = "API_CALL_FAILURE_ONE_POST";

export const API_CALL_REQUEST_USERS = "API_CALL_REQUEST_USERS";
export const API_CALL_SUCCESS_USERS = "API_CALL_SUCCESS_USERS";
export const API_CALL_FAILURE_USERS = "API_CALL_FAILURE_USERS";

export const API_CALL_REQUEST_COMMENTS = "API_CALL_REQUEST_COMMENTS";
export const API_CALL_SUCCESS_COMMENTS = "API_CALL_SUCCESS_COMMENTS";
export const API_CALL_FAILURE_COMMENTS = "API_CALL_FAILURE_COMMENTS";

export const SET_PAGINATION = "SET_PAGINATION";
