export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";

export const API_CALL_REQUEST_ONE_POST = "API_CALL_REQUEST_ONE_POST";
export const API_CALL_SUCCESS_ONE_POST = "API_CALL_SUCCESS_ONE_POST";
export const API_CALL_FAILURE_ONE_POST = "API_CALL_FAILURE_ONE_POST";
